site_name: MEPhI Docs
theme: alabaster

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - _static/javascript/mathconf.js
  # - _static/javascript/mathjax.js

extra_css:
  - _static/stylesheets/extra.css
